version: '3.6'
services:
  iris:
    container_name: backend-lojavirtual
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 51773
      - 52773:52773
      - 53773
    volumes:
      - ./:/irisdev/app
      - ./data:/durable 
    environment: 
      - ISC_DATA_DIRECTORY=/durable